### ISSUE TITLE
`Bug` Compiling error for 4.3.8

### ISSUE THREAD

**Issue by karli2000** [Blackymas/NSPanel_HA_Blueprint#2141]
### TFT Version

4.3.7 

### ESPHome Version

2024.5.5

### Blueprint Version

4.3.8

### Panel Model

EU

### What is the bug?

Not able to compile 4.3.8, see ESPHome logs

### Steps to Reproduce

Update blueprint in HA
Run "Clean Build Files" ins ESPHome
Run "Install" in ESPHome

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME ######

  device_name: "nspanel"
  wifi_ssid: "***********"
  wifi_password: "***********"

##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

 
##### DO NOT CHANGE ANYTHING! #####
```

### ESPHome Logs

INFO ESPHome 2024.5.5
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Detected timezone 'Europe/Vienna'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanel/src/esphome/components/adc/adc_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_connection.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_server.o
Compiling .pioenvs/nspanel/src/esphome/components/api/list_entities.o
Compiling .pioenvs/nspanel/src/esphome/components/api/proto.o
Compiling .pioenvs/nspanel/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/nspanel/src/esphome/components/api/user_services.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/nspanel/src/esphome/components/button/button.o
Compiling .pioenvs/nspanel/src/esphome/components/display/display.o
Compiling .pioenvs/nspanel/src/esphome/components/display/display_buffer.o
Compiling .pioenvs/nspanel/src/esphome/components/display/rect.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/core.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/nspanel/src/esphome/components/factory_reset/button/factory_reset_button.o
Compiling .pioenvs/nspanel/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/gpio/switch/gpio_switch.o
Compiling .pioenvs/nspanel/src/esphome/components/homeassistant/time/homeassistant_time.o
Compiling .pioenvs/nspanel/src/esphome/components/json/json_util.o
Compiling .pioenvs/nspanel/src/esphome/components/ledc/ledc_output.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger_esp32.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger_esp8266.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger_host.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger_libretiny.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger_rp2040.o
Compiling .pioenvs/nspanel/src/esphome/components/md5/md5.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_esp32.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_host.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_libretiny.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_rp2040.o
Compiling .pioenvs/nspanel/src/esphome/components/network/util.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_commands.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_component.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_upload_arduino.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_upload_idf.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/sensor/nextion_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/text_sensor/nextion_textsensor.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/ha_components.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/hardware.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/icons.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/mdiicons.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/nextion_components.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/pages.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/text.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/upload_tft.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/utilities.o
Compiling .pioenvs/nspanel/src/esphome/components/nspanel_ha_blueprint/versioning.o
Compiling .pioenvs/nspanel/src/esphome/components/ntc/ntc.o
Compiling .pioenvs/nspanel/src/esphome/components/number/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number_call.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number_traits.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_libretiny.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_component.o
Compiling .pioenvs/nspanel/src/esphome/components/output/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/output/float_output.o
Compiling .pioenvs/nspanel/src/esphome/components/psram/psram.o
Compiling .pioenvs/nspanel/src/esphome/components/resistance/resistance_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/restart/button/restart_button.o
Compiling .pioenvs/nspanel/src/esphome/components/rtttl/rtttl.o
Compiling .pioenvs/nspanel/src/esphome/components/script/script.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select_call.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select_traits.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/filter.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/lwip_sockets_impl.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/socket.o
Compiling .pioenvs/nspanel/src/esphome/components/switch/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/switch/switch.o
Compiling .pioenvs/nspanel/src/esphome/components/template/binary_sensor/template_binary_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/template/number/template_number.o
Compiling .pioenvs/nspanel/src/esphome/components/template/select/template_select.o
Compiling .pioenvs/nspanel/src/esphome/components/template/sensor/template_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/template/switch/template_switch.o
Compiling .pioenvs/nspanel/src/esphome/components/template/text_sensor/template_text_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/text_sensor/filter.o
Compiling .pioenvs/nspanel/src/esphome/components/text_sensor/text_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/time/automation.o
Compiling .pioenvs/nspanel/src/esphome/components/time/real_time_clock.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp32_arduino.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp8266.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp_idf.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_libretiny.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_rp2040.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_debugger.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_esp_idf.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_libretiny.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_pico_w.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi_signal/wifi_signal_sensor.o
Compiling .pioenvs/nspanel/src/esphome/core/application.o
Compiling .pioenvs/nspanel/src/esphome/core/color.o
Compiling .pioenvs/nspanel/src/esphome/core/component.o
Compiling .pioenvs/nspanel/src/esphome/core/component_iterator.o
Compiling .pioenvs/nspanel/src/esphome/core/controller.o
Compiling .pioenvs/nspanel/src/esphome/core/entity_base.o
Compiling .pioenvs/nspanel/src/esphome/core/helpers.o
Compiling .pioenvs/nspanel/src/esphome/core/log.o
Compiling .pioenvs/nspanel/src/esphome/core/ring_buffer.o
Compiling .pioenvs/nspanel/src/esphome/core/scheduler.o
Compiling .pioenvs/nspanel/src/esphome/core/string_ref.o
Compiling .pioenvs/nspanel/src/esphome/core/time.o
Compiling .pioenvs/nspanel/src/esphome/core/util.o
Compiling .pioenvs/nspanel/src/main.o
Generating LD script .pioenvs/nspanel/memory.ld
Compiling .pioenvs/nspanel/app_trace/app_trace.o
Compiling .pioenvs/nspanel/app_trace/app_trace_util.o
Compiling .pioenvs/nspanel/app_trace/host_file_io.o
Compiling .pioenvs/nspanel/app_trace/gcov/gcov_rtio.o
Compiling .pioenvs/nspanel/app_update/esp_ota_ops.o
Archiving .pioenvs/nspanel/esp-idf/app_trace/libapp_trace.a
Compiling .pioenvs/nspanel/app_update/esp_app_desc.o
Compiling .pioenvs/nspanel/asio/asio/asio/src/asio.o
Archiving .pioenvs/nspanel/esp-idf/app_update/libapp_update.a
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_common.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_common_loader.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_clock_init.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_flash.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_mem.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_random.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_random_esp32.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_utility.o
Compiling .pioenvs/nspanel/bootloader_support/src/esp_image_format.o
Compiling .pioenvs/nspanel/bootloader_support/src/flash_encrypt.o
Compiling .pioenvs/nspanel/bootloader_support/src/secure_boot.o
Compiling .pioenvs/nspanel/bootloader_support/src/flash_partitions.o
Compiling .pioenvs/nspanel/bootloader_support/src/flash_qio_mode.o
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_flash_config_esp32.o
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:2062:16: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
             disp1->send_command("tm_esphome.en=0");
                ^~~~~~~~~~~~
                send_command_
Compiling .pioenvs/nspanel/bootloader_support/src/bootloader_efuse.o
Compiling .pioenvs/nspanel/bootloader_support/src/idf/bootloader_sha.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborencoder_close_container_checked.o
Archiving .pioenvs/nspanel/esp-idf/bootloader_support/libbootloader_support.a
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:2446:14: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
           disp1->send_command("tm_esphome.en=0");
              ^~~~~~~~~~~~
              send_command_
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborencoder.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborerrorstrings.o
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:2605:18: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
               disp1->send_command("back_page_id=1");
                  ^~~~~~~~~~~~
                  send_command_
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborparser_dup_string.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborparser.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborpretty_stdio.o
/data/packages/566b10a3/esphome/nspanel_esphome_addon_upload_tft.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_addon_upload_tft.yaml:127:83: error: no matching function for call to 'esphome::nextion::Nextion::upload_tft(uint32_t&, bool)'
           id(tft_upload_result) = disp1->upload_tft(baud_rate, !disp1->is_setup());
                                                                                   ^
In file included from src/esphome/components/nextion/automation.h:3,
                 from src/esphome.h:39,
                 from src/main.cpp:3:
src/esphome/components/nextion/nextion.h:926:8: note: candidate: 'bool esphome::nextion::Nextion::upload_tft()'
   bool upload_tft();
        ^~~~~~~~~~
src/esphome/components/nextion/nextion.h:926:8: note:   candidate expects 0 arguments, 2 provided
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborpretty.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cbortojson.o
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:253:16: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
               disp1->send_command(cmd.c_str());
                ^~~~~~~~~~~~
                send_command_
Compiling .pioenvs/nspanel/cbor/tinycbor/src/cborvalidation.o
Compiling .pioenvs/nspanel/cbor/tinycbor/src/open_memstream.o
Compiling .pioenvs/nspanel/cmock/CMock/src/cmock.o
Archiving .pioenvs/nspanel/esp-idf/cbor/libcbor.a
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:790:18: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
                 disp1->send_command("prg_timer.en=0");
                  ^~~~~~~~~~~~
                  send_command_
Compiling .pioenvs/nspanel/coap/libcoap/src/address.o
Archiving .pioenvs/nspanel/esp-idf/cmock/libcmock.a
Compiling .pioenvs/nspanel/coap/libcoap/src/async.o
Compiling .pioenvs/nspanel/coap/libcoap/src/block.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_asn1.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_cache.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_debug.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_event.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_hashkey.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_io.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_mbedtls.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_notls.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_prng.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_session.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_tcp.o
Compiling .pioenvs/nspanel/coap/libcoap/src/coap_time.o
Compiling .pioenvs/nspanel/coap/libcoap/src/encode.o
Compiling .pioenvs/nspanel/coap/libcoap/src/mem.o
Compiling .pioenvs/nspanel/coap/libcoap/src/net.o
Compiling .pioenvs/nspanel/coap/libcoap/src/option.o
Archiving .pioenvs/nspanel/esp-idf/asio/libasio.a
Compiling .pioenvs/nspanel/coap/libcoap/src/pdu.o
Compiling .pioenvs/nspanel/coap/libcoap/src/resource.o
Compiling .pioenvs/nspanel/coap/libcoap/src/str.o
Compiling .pioenvs/nspanel/coap/libcoap/src/subscribe.o
Compiling .pioenvs/nspanel/coap/libcoap/src/uri.o
Compiling .pioenvs/nspanel/console/commands.o
Compiling .pioenvs/nspanel/console/esp_console_repl.o
Compiling .pioenvs/nspanel/console/split_argv.o
Compiling .pioenvs/nspanel/console/linenoise/linenoise.o
Compiling .pioenvs/nspanel/console/argtable3/arg_cmd.o
Archiving .pioenvs/nspanel/esp-idf/coap/libcoap.a
Compiling .pioenvs/nspanel/console/argtable3/arg_date.o
Compiling .pioenvs/nspanel/console/argtable3/arg_dbl.o
Compiling .pioenvs/nspanel/console/argtable3/arg_dstr.o
Compiling .pioenvs/nspanel/console/argtable3/arg_end.o
Compiling .pioenvs/nspanel/console/argtable3/arg_file.o
Compiling .pioenvs/nspanel/console/argtable3/arg_hashtable.o
Compiling .pioenvs/nspanel/console/argtable3/arg_int.o
Compiling .pioenvs/nspanel/console/argtable3/arg_lit.o
Compiling .pioenvs/nspanel/console/argtable3/arg_rem.o
Compiling .pioenvs/nspanel/console/argtable3/arg_rex.o
Compiling .pioenvs/nspanel/console/argtable3/arg_str.o
Compiling .pioenvs/nspanel/console/argtable3/arg_utils.o
Compiling .pioenvs/nspanel/console/argtable3/argtable3.o
Compiling .pioenvs/nspanel/cxx/cxx_exception_stubs.o
Compiling .pioenvs/nspanel/cxx/cxx_guards.o
Compiling .pioenvs/nspanel/driver/gpio.o
Archiving .pioenvs/nspanel/esp-idf/console/libconsole.a
Compiling .pioenvs/nspanel/driver/i2c.o
*** [.pioenvs/nspanel/src/main.o] Error 1
========================= [FAILED] Took 202.69 seconds =========================

### Home Assistant Logs

Error is during compiling, no log entry in HA-logs

**Comment by edwardtfn** [comment]
> * /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml: In lambda function:
>   /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:2062:16: error: 'class esphome::nextion::Nextion' has no member named 'send_command'; did you mean 'send_command_'?
>   disp1->send_command("tm_esphome.en=0");
>   ^~~~~~~~~~~~
>   send_command_

This shouldn't be an issue with ESPHome v2024.5.
I'm not at home right now, but when I come back I will try to duplicate it and come back to you.

**Comment by edwardtfn** [comment]
I could compile with exactly the same yaml you provided and it went all fine. Also using ESPHome v2024.5.5 here.

**Comment by karli2000** [comment]
Just tried it again, restarted my whole HA System, even set the ESPHome compile_process_limit (the hardware is a Raspberry PI 4 with 4GB Ram, never had a issue with memory so far during compilation), cleaned all build files and still the same error. 
Any idea what could be the problem?

**Comment by kakaki** [comment]
Same problem, can't compile on 2024.5.5, even tried with 2024.6.0 dev still can't.

**Comment by edwardtfn** [comment]
I don't think this is memory related. Looks like older components files in the cache. I can change the code to use other functions, but that shouldn't be the way.
Anyways, I will look at that option when I get home.

Could you please try using arduino and let me know if it compiles (or which error message you have in that case)? Just add this to your yaml:

```yaml
esp32:
  framework:
    type: arduino
```

**Comment by synack666** [comment]
same here:

INFO ESPHome 2024.5.5
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.8
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanel/src/esphome/components/adc/adc_sensor.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_commands.o
*** [.pioenvs/nspanel/src/esphome/components/nextion/nextion_upload.o] Source `src/esphome/components/nextion/nextion_upload.cpp' not found, needed by target `.pioenvs/nspanel/src/esphome/components/nextion/nextion_upload.o'.
========================== [FAILED] Took 6.30 seconds ==========================

**Comment by edwardtfn** [comment]
This is a different error message. Have you tried cleaning build files?

**Comment by xenos910** [comment]
I also encountered a compile failure. In addition to clearing the build, you also need to clean the external components, and then it will compile successfully.

**Comment by Phalen** [comment]
> clearing the build, you also need to clean the external components,
Can you provide details on how this is done or a faq page for it? im getting the same.

**Comment by edwardtfn** [comment]
> I also encountered a compile failure. In addition to clearing the build, you also need to clean the external components, and then it will compile successfully.

How do you clear the components?

**Comment by synack666** [comment]
ok, my stupid, with "clean build files" everything is ok

**Comment by ChaoticAlex** [comment]
Same problem. INFO Configuration is valid but it will cause an error when updated. Even after "cleaning build files"

**Comment by karli2000** [comment]
tried it with arduino framework, same result, see attached log.
Is there any way i can clean the cache files manually?


> I don't think this is memory related. Looks like older components files in the cache. I can change the code to use other functions, but that shouldn't be the way. Anyways, I will look at that option when I get home.
> 
> Could you please try using arduino and let me know if it compiles (or which error message you have in that case)? Just add this to your yaml:
> 
> ```yaml
> esp32:
>   framework:
>     type: arduino
> ```


[logs_nspanel_run (1).txt](https://github.com/user-attachments/files/15759084/logs_nspanel_run.1.txt)

**Comment by xenos910** [comment]
> > I also encountered a compile failure. In addition to clearing the build, you also need to clean the external components, and then it will compile successfully.
> 
> How do you clear the components?

delete all files in the "external_components" folder

**Comment by ChaoticAlex** [comment]
> > > 我也遇到编译失败的情况，除了清除build之外，还需要清理外部的组件，然后就可以编译成功了。
> > 
> > 
> > 如何清除组件？
> 
> 删除“external_components”文件夹中的所有文件

It work, thx

**Comment by famviuf** [comment]
> > > I also encountered a compile failure. In addition to clearing the build, you also need to clean the external components, and then it will compile successfully.
> > 
> > 
> > How do you clear the components?
> 
> delete all files in the "external_components" folder

where can i find the "external_components" folder?

**Comment by MicroFire33** [comment]
After updating Home Assistant 2024.6.2.
Everything works without deleting anything!!!

**Comment by karli2000** [comment]
Same for me, after updating Home Assistant to 2024.6.2 it compiles without problems, so you can close this!

Thank your all for the great work, i really love your blueprint!
