### ISSUE TITLE
notification icon won't disapear

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#937]
Hello,

I'm struggling with an issue
After I send a notification like this
```
service: esphome.myswitch_notification_show
data:
  label: xx
  text: xx
```

and then wait for the homepage to be shown again, I see a notification icon.
when I click it, I see the message again.
and when I hit the green button the home screen shows including the notification icon.
but now I cannot click it anymore.

also at this point the clear service won't work anymore
```
service: esphome.myswitch_notification_clear
data: {}
```
the clear service only works if I haven't tried to click the green button yet

**Comment by deejaybeam** [comment]
Which version(s) do you have installed?
You can see this on the blue-screen when rebooting the device:
- TFT: ?
- ESPHome: ?
- Blueprint: ?

**Comment by bkbartk** [comment]
TFT: 3.4
    ESPHome: 3.4
    Blueprint: 3.4

**Comment by deejaybeam** [comment]
Maybe you found some logs?
I can confirm that this works with 3.4:
- call the service show notification
- wait to go back to homepage -> notification icon appears
- click on the notification icon to open the message again
- confirm with green button closes message and remove notification icon on home screen

**Comment by bkbartk** [comment]
I only see this one, but I think it's unrelated
`Error while executing automation automation.nspanel_slaapkamer: UndefinedError: 'dict object' has no attribute 'pics'`
what I also noticed is that when I send a notification while the screen is in sleepmode the icon won't show up,
I'm still able to click where the icon is supposed to be.

**Comment by edwardtfn** [comment]
Looks like a bug and I think it was already fixed in `dev`. I will double check when I get back home next week.

**Comment by edwardtfn** [comment]
This is fixed in `dev` and will be included in the next release.
