### ISSUE TITLE
after upgrading blueprint+esphome+tft to 3.2.1 only loading page (Solved)

### ISSUE THREAD

**Issue by pkleingu** [Blackymas/NSPanel_HA_Blueprint#563]
Solved : after creating and filling in a Weather entity in de blueprint is finaly works.
This was not a problem with 3.1
after upgrading blueprint+esphome+tft to 3.2.1 only loading page
how can i troubleshoot this problem?
I have update/deleted everything severral times, rebooted ect., no effect

error I found:

2023-03-29 15:24:22.969 ERROR (MainThread) [homeassistant.components.automation.nspanel_black] NSPanel -black: Choose at step 2: choice 3: Choose at step 2: home page: Error executing script. Error rendering template for variables at pos 28: AttributeError: 'list' object has no attribute 'lower'
2023-03-29 15:24:22.971 ERROR (MainThread) [homeassistant.components.automation.nspanel_black] NSPanel -black: Choose at step 2: choice 3: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2023-03-29 15:24:22.971 ERROR (MainThread) [homeassistant.components.automation.nspanel_black] NSPanel -black: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2023-03-29 15:24:22.979 ERROR (MainThread) [homeassistant.components.automation.nspanel_black] Error while executing automation automation.nspanel_black: AttributeError: 'list' object has no attribute 'lower'

Are there primary feelds in the blueprint that have to be editted to get it work again?
![Schermafbeelding 2023-03-29 143905](https://user-images.githubusercontent.com/71530042/228539266-40241313-cb7f-48be-a022-c9e0c16f2b14.jpg)
![PXL_20230329_121155108](https://user-images.githubusercontent.com/71530042/228539319-678f847e-d11a-4b9c-81ef-5583e9f9ea36.jpg)
![PXL_20230329_121216110](https://user-images.githubusercontent.com/71530042/228539345-beefdf7a-f290-4b3c-b7fc-c71a6e2ea90e.jpg)

![Schermafbeelding 2023-03-29 145242](https://user-images.githubusercontent.com/71530042/228541264-22998b01-e679-4461-8c05-3430fa7084b3.jpg)
![Schermafbeelding 2023-03-29 150807](https://user-images.githubusercontent.com/71530042/228546083-f7fc09cb-6439-4440-8657-f21c0562bb4a.jpg)

**Comment by edwardtfn** [comment]
Do you have an indoor temperature sensor set? If not, could you please set something just for testing purposes?

This looks like the issue resolved by #561, but I want to investigate more if there are other sensors triggering the same error when missing.

**Comment by pkleingu** [comment]
Solved : after creating and filling in a Weather entity in de blueprint is finaly works.
This was not a problem with 3.1

**Comment by edwardtfn** [comment]
> This was not a problem with 3.1

That's true. It was not a problem with 3.2 as well. It was an issue introduced when trying to fix another issue related to showing the page "Loading..." when a sensor was unavailable.
This new bug was already fixed, but still in de branch also. With that you should be able to use without the weather or internal temperature.
Sorry for the inconvenience. 😩
