### ISSUE TITLE
`Bug` Can't build with ESPHome 2024.3.0

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#1975]
### TFT Version

latest

### ESPHome Version

latest

### Blueprint Version

latest

### Panel Model

EU

### What is the bug?

When trying to build with latest ESPHome version, it fails with this log:
```
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: error: 'get_ip_address' is not a member of 'esphome::network'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: note: suggested alternative: 'get_ip_addresses'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
                                                                         get_ip_addresses
```

### Your Panel's YAML

```yaml
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
    refresh: 300s

##### My customization - Start #####
wifi:
  networks:
    - id: !extend wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
      ##### advanced config - uncomment to use static IP-Config #####
      manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
        dns1: ${dns}
  # domain: ${domain}
  ##### Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

ota:
  password: ${ota_password}

api:
  encryption:
    key: ${api_password}

esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel1_part.csv"
##### My customization - End #####
```

**Comment by X-Ryl669** [comment]
Please notice that I have @main on the remote package definition (so it should download the latest version), but I still get this in the ESPHome build dialog:
```
INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/nspanel1.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Reverting changes to https://github.com/Blackymas/NSPanel_HA_Blueprint@main -> 01161b9f254e11d60c4ac0f4a93763226bd23eca
INFO Detected timezone 'Europe/Paris'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel1 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
```

Notice the **Reverting changes** line that seems to reset the head to a much older version, so I can't fetch the version v4.3.1 that should have fixed this issue. I don't understand where this revert comes from.

**Comment by X-Ryl669** [comment]
Please see [here](https://github.com/esphome/issues/issues/4221). It seems the `refresh`key is ignored for remote_package.

**Comment by giannoug** [comment]
Same issue here.

Home Assistant Core 2024.3.3
ESPHome 2024.3.0
NSPanel_HA_Blueprint pinned to v4.2.6

I have multiple panels and they now require TTL flashing 😅 so I want to stay at the latest arduino version until I have time to flash each one to idf but I want to keep updated with ESPHome in the meantime.

Release v4.3.1 mentions a fix that I believe could be related to this issue, and if true I think that all previous versions of NSPanel_HA_Blueprint are broken: https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.3.1

> Patch v4.3.1 focuses primarily on ensuring full compatibility with the latest ESPHome v2024.3.0 IP address format changes, crucial for the smooth compilation and operation of the NSPanel project.

**Comment by X-Ryl669** [comment]
See #1821 for how to build a ESP-IDF version that's compatible with your Arduino's partition layout. That's what I'm using and it's working fine. The issue in ESPHome has been identified. It's mainly due to ESPHome silently reverting the package's git repository to the previous version when it encounter a YAML error on the new version.

But since it doesn't tell you the error, you can't fix it and you're struck to a non functional system. On my case, it was the line
```
      - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
```

That caused the breakage. The file was moved between version v4.2.6 and v4.3.1 so the generated YAML with the old path failed to build. Update the path to the new version and it should work.

**Comment by giannoug** [comment]
> See https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1821 for how to build a ESP-IDF version that's compatible with your Arduino's partition layout.

I just removed the first panel from the wall and setup my tools 😅 I'm going to flash them because I'll have to eventually, but thanks for the tip!

**Comment by ali96adil** [comment]
**What's the issue? Why am I getting this error, and how can it be resolved?**

`/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: error: 'get_ip_address' is not a member of 'esphome::network'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: note: suggested alternative: 'get_ip_addresses'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
                                                                         get_ip_addresses`

**Comment by giannoug** [comment]
> how can it be resolved?

Personally I ended up upgrading all my panels (with TTL) to the latest version

**Comment by ali96adil** [comment]
> Personally I ended up upgrading all my panels (with TTL) to the latest version

How do I manually upload the file?  with TTL
![Uploading Screenshot 2024-03-28 at 2.20.49 AM.png…]()

**Comment by ali96adil** [comment]
<img width="1213" alt="Screenshot 2024-03-28 at 2 26 05 AM" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/70801949/272007fc-4a04-4cf1-bc7a-7caaf316b7df">

**Comment by giannoug** [comment]
@ali96adil Check the release notes: https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.3.0

**Comment by X-Ryl669** [comment]
You probably are using advanced mode in YAML. The files have changed position so you need to update the file location. In case of doubt, just replace the `ref` key in your YAML from `main` to `v4.3.1`, clean the project and try to build again. It'd give you the errors. Once fixed, you can put back the `main` reference.

**Comment by jaymunro** [comment]
I'm also getting this "Reverting changes" behaviour in a completely different compile (https://github.com/jaymunro/esphome_firmware/blob/continued-conversation/wake-word-voice-assistant/esp32-s3-box-3.yaml).

It's making testing very troublesome as no errors are reported anymore while developing. It strikes me this new behaviour is desirable for end users in a production environment, but there must be some new flag to turn this off, surely.

**Comment by X-Ryl669** [comment]
We have discussed this issue on Discord. There's no message (and no way to have one) in current code, except by going into the docker and deleting the Git repository for the package. If a repository exists, its current HEAD is remembered and restored upon error. If it doesn't exist, this doesn't happen and you get the error reported.

**Comment by jaymunro** [comment]
I found another work around was to create another branch and update the reference in ESPHome, but it's not practical for the long term.
I hope there's an issue on the matter and the devs are aware.

**Comment by gednet** [comment]
Same problem here. I don't knowhow i can fix it. There is solution for this issue?

ESPHome 2024.3.1

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/96190783/8ef98e62-a10e-4cc8-ae6c-457e717e5ab0)

/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2713:73: error: 'get_ip_address' is not a member of 'esphome::network'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2713:73: note: suggested alternative: 'get_ip_addresses'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
                                                                         get_ip_addresses

**Comment by X-Ryl669** [comment]
Change your ref in your YAML from `main` to `v4.3.1`. Clean, build, fix error, repeat. Once built, change back to `main`

**Comment by gednet** [comment]
> Change your ref in your YAML from `main` to `v4.3.1`. Clean, build, fix error, repeat. Once built, change back to `main`

Cleaned, changed to ref to `v4.3.1` and i have other error:

Why? please help.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/96190783/a933f3d2-c866-45d8-8595-c76168a0b514)

**Comment by edwardtfn** [comment]
Are you still having these issues with v4.3.2?

**Comment by gednet** [comment]
Yes, still the same issue when i try to compilate with v4.3.2:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/96190783/097c60f7-457b-4ce5-b22a-9ae34bcad22f)
No matter what i do: clean build files, change ref ver, try to compilate with 4.3.2 and after that i try to back to main ref.

**Comment by edwardtfn** [comment]
Could you please share the logs before this error message.
The error is related to old code being used. I wanna find in the logs why the newest code isn't downloaded.

**Comment by spitfire** [comment]
same here after changing ref, commenting out nspanel_advanced, cleaning build files and trying to build again:
```
/config/.esphome/packages/03e2381c/esphome/nspanel_esphome_core.yaml: In lambda function:
/config/.esphome/packages/03e2381c/esphome/nspanel_esphome_core.yaml:2735:101: error: request for member 'c_str' in 'component.nspanel_ha_blueprint::NextionComponent::component_id', which is of non-class type 'char [15]'
           if (component.is_current_page) disp1->send_command_printf("vis %s,%i", component.component_id.c_str(), show ? 1 : 0);
```

**Comment by gednet** [comment]
> Could you please share the logs before this error message. The error is related to old code being used. I wanna find in the logs why the newest code isn't downloaded.

Here is log before cleaning build files:
[logs_nspanelweranda_run (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14875858/logs_nspanelweranda_run.1.txt)

And full log after cleaning buld files for the nspanel:
[logs_nspanelweranda_run (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14875864/logs_nspanelweranda_run.2.txt)

If i can replace some file or if you want me to check some solution feel free. I'm ready. I want to update because i'm after big chcange in my home and i try to prepare new configuration on the newest version.

**Comment by edwardtfn** [comment]
@gednet, by looking at your logs I just realized you are using Arduino, so this is different than the original case which was ESP-IDF.

Do you mind sharing your panel's yaml? Please remove any sensitive info before sharing.

**Comment by ali96adil** [comment]
The same problem after several attempts did not solve the problem

[logs_nsali_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14878389/logs_nsali_run.txt)
[logs_nsali_run-2.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14878398/logs_nsali_run-2.txt)
[logs_nsali_run-3.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14878400/logs_nsali_run-3.txt)
[logs_nsali_run-4.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14878407/logs_nsali_run-4.txt)

**Comment by edwardtfn** [comment]
@ali96adil, could you please share your panel's yaml? Please remove any sensitive information before sharing.

**Comment by ali96adil** [comment]
> @ali96adil, could you please share your panel's yaml? Please remove any sensitive information before sharing.

`substitutions:
  # Settings - Editable values
  device_name: "nsali"
  friendly_name: "nsali"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml `

**Comment by edwardtfn** [comment]
Your logs shows a mix of frameworks and tags used, so I believe you have tried different things, right?
Could you please share the logs when using this yaml you just shared? Please clean build files before trying compiling to capture the logs.

**Comment by gednet** [comment]
> @gednet, by looking at your logs I just realized you are using Arduino, so this is different than the original case which was ESP-IDF.
> 
> Do you mind sharing your panel's yaml? Please remove any sensitive info before sharing.

Ok. But i don't understand why still is arduino framework, when in nspanel_esphome_core.yaml from lin no 103 is right definition esp-idf framework type.

Here is my original yaml

substitutions:

###### CHANGE ME START ######
  device_name: "nspanelweranda" 
  nextion_update_url: "http://192.168.xxx.xxx:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
#  web_password: !secret nspanel_web_password
#  wifi_password: !secret wifi_password

wifi:
  networks:
    - id: wifi_wlan
      ssid: !secret wifi_ssid
      password: !secret wifi_password
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.xx.yy
    gateway: 192.168.xx.xx
    subnet: 255.255.255.0
    dns1: 192.168.xx.xx

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: never
##### DO NOT CHANGE ANYTHING! #####

After i have read your suggestion i put in my yaml all framework definition from nspanel_esphome_core.yaml. 
esp32:
  board: esp32dev
  framework:
    type: esp-idf

But compilation still gave me the same error.
[logs_nspanelweranda_run (3).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14884737/logs_nspanelweranda_run.3.txt)

**Comment by edwardtfn** [comment]
Could you please try changing from `refresh: never` to `refresh: 30s`?

**Comment by gednet** [comment]
Nothing changed :(

**Comment by X-Ryl669** [comment]
> Could you please try changing from `refresh: never` to `refresh: 30s`?

That doesn't work on ESPHome. He has to change the ref to refresh, the refresh time is ignored upon error.

**Comment by morpheus8888** [comment]
I have the same problem and cannot build

**Comment by edwardtfn** [comment]
Please try changing from `ref: main` to `ref: beta` in the `remote_package` area. Right now beta have exactly the same code as main, but this will force a reload of the files.

**Comment by sztupy** [comment]
I have the same issue with the latest version `v4.3.13`. Anything I try ESPHome Builder reverts it back to 4.3.12. I even removed the entire ESPHome builder volume and reinstalled ESPHome builder to make sure it all of it's caches are gone. On the first try it will download `main` then return an error saying `nspanel_esphome.yaml is not found`. If you afterwards retry, it will silently download `v4.3.12` instead of `main` / `v4.3.13`, and use that.

I have to fully uninstall/reinstall ESPHome Builder again and clear it's docker data folder to get the chance for it to download main again.

Fortunately I don't use the climate features so I don't really need the 4.3.13 update, but it's still odd that it works like this
